### ISSUE TITLE
Requirements to install Cloud Agent using ARM

### ISSUE THREAD

**Issue by alexmpmenezes** [Qualys-Public/CloudAgent-Azure-ARMTemplate#1]
Hi. 
Qualys has released the integration to install [Cloud Agents using Azure Security Center](https://discussions.qualys.com/docs/DOC-5823-deploying-qualys-cloud-agents-from-microsoft-azure-security-center). The process in the Security Center requires a "License Code" and "Public Key" whereas the ARM template parameter only accept the "License Code" parameters.

Also, before deploying the Cloud Agent using ARM, do I need to create any other resource in Azure (like a Qualys solution?) This is not very clear on the documentation.

 Thanks,
Alex

**Comment by mkhanal1** [comment]
Hi Alex,

The installation via ARM template & ASC both uses VM extension, however, ARM Template is meant only for installation, unlike ASC method which, in addition, sends the Vulnerability information to ASC and in turn requires a public key for its validation.
